### ISSUE TITLE
Receiving "TypeError: Object.keys called on non-object" in v0.10.38

### ISSUE THREAD

**Issue by kevinold** [isaacs/once#5]
I am seeing an issue where this is generated when I'm requiring and trying to use once in Node 0.10.38.

'use strict';

var once = require('once');
var cb = once(cb);

/home/vagrant/new_nuztap_frontend/node_modules/once/node_modules/wrappy/wrappy.js:27
      Object.keys(cb).forEach(function (k) {
             ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at wrapper (/home/vagrant/new_nuztap_frontend/node_modules/once/node_modules/wrappy/wrappy.js:27:14)
    at Object.<anonymous> (/home/vagrant/new_nuztap_frontend/lib/config/harvest_job.js:4:10)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/home/vagrant/new_nuztap_frontend/server.js:27:18)

I do not see any requirements that says I can't use v0.10.38 with this module.

**Comment by kevinold** [comment]
Disregard, I see my error
